alias config='/usr/bin/git --git-dir=/home/dennis/.cfg/ --work-tree=/home/dennis'
alias configc='config commit -am '
alias configpom='config push origin main'
alias configp='config pull'
alias bashrc='vim .bashrc'
